# Generated by Django 3.2.25 on 2026-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancerequest',
            name='intake_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
