# Generated by Django 3.2.25 on 2026-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clearancerequest_intake_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionstatus',
            name='student_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
