# Generated by Django 6.0.7 on 2026-08-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_sectionstatus_student_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="ocr_fields_json",
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
