# Generated by Django 3.2.25 on 2026-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161115_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Account', max_length=250),
        ),
        migrations.AlterField(
            model_name='cc',
            name='name',
            field=models.CharField(default='CC', max_length=250),
        ),
        migrations.AlterField(
            model_name='gymkhana',
            name='name',
            field=models.CharField(default='Gymkhana', max_length=250),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(default='Lab', max_length=250),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default='Library', max_length=250),
        ),
        migrations.AlterField(
            model_name='onlinecc',
            name='name',
            field=models.CharField(default='OnlineCC', max_length=250),
        ),
        migrations.AlterField(
            model_name='submitthesis',
            name='name',
            field=models.CharField(default='Submit Thesis', max_length=250),
        ),
    ]
