# Generated by Django 6.0.7 on 2026-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20260729_1840"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="btp_doc_title",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="student",
            name="btp_form_no",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="btp_plagiarism",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="intake_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="offer_letter_name",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="student",
            name="vacant_room_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
