# Generated by Django 6.0.7 on 2026-07-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_student_btp_doc_title_student_btp_form_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportOffice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("webmail", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=250)),
                ("office_role", models.CharField(max_length=100)),
                ("hostel", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="bh1_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="bh2_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="bh3_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="bh5_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="lucs_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="medical_unit_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="nad_cell_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="section_feedback",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="student",
            name="sports_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="store_release_approval",
            field=models.BooleanField(default=False),
        ),
    ]
