"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Load the repo-root .env for plain `manage.py runserver` / local tooling, so it
# sees the same values docker-compose.yml passes into the containers — no more
# manually exporting DATABASE_URL and it drifting out of sync with .env.
# No-op if the file doesn't exist; never overrides a real env var that's
# already set (e.g. the ones docker-compose injects directly into the container).
load_dotenv(os.path.join(BASE_DIR, os.pardir, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set the DJANGO_SECRET_KEY environment variable — never commit
# a real production key. The fallback below is a dev-only placeholder.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'z=dqu984s9ps!l(2s)xqj!53852bc5%_+e3ayui#85z!j+a%%z',  # dev-only default
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=False in production. Defaults to True to keep local
# `python manage.py runserver` working with no setup.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Comma-separated list, e.g. DJANGO_ALLOWED_HOSTS=nodues.lnmiit.ac.in,10.0.0.5
# Defaults to '*' only for local development convenience.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()
]

# Comma-separated list of scheme+host origins allowed to submit CSRF-protected
# requests, e.g. DJANGO_CSRF_TRUSTED_ORIGINS=https://nodues.lnmiit.ac.in
#
# Always trusts the local dev origins (Vite on :5173, Django on :8000)
# *in addition to* whatever DJANGO_CSRF_TRUSTED_ORIGINS says, rather than the
# env var replacing them. Otherwise the same .env used for a Docker/production
# domain (e.g. just "https://nodues.lnmiit.ac.in") silently breaks local
# `manage.py runserver` + `npm run dev` with a CSRF 403, since that one value
# would be the *only* trusted origin instead of an addition to the dev ones.
# Trusting localhost/127.0.0.1 costs nothing in production — an attacker can't
# make a real browser's Origin header say "localhost" against a remote server.
_DEV_CSRF_ORIGINS = [
    'http://localhost:5173', 'http://127.0.0.1:5173',
    'http://localhost:8000', 'http://127.0.0.1:8000',
    'http://localhost', 'http://127.0.0.1',
]
_configured_origins = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(_DEV_CSRF_ORIGINS + _configured_origins))



# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves Django's own static files (admin CSS/JS) without nginx needing a shared volume
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
#
# PostgreSQL only — see docs/SCALING.md. Inside `docker-compose.yml`, the
# `backend` container gets a real DATABASE_URL (pointing at the `db` service)
# injected directly by Compose, so the branch below never runs there.
#
# Outside Compose (plain `manage.py runserver`, no DATABASE_URL in the actual
# environment), build one from the same POSTGRES_* values in .env that
# docker-compose.yml itself uses — via `localhost:POSTGRES_PORT` instead of
# the Docker-internal `db:5432` — so there's exactly one place (.env) to keep
# credentials in sync, not two. `docker compose up -d db` gets you a real
# Postgres at that same host/port with zero extra setup.
_local_db_url = 'postgres://{user}:{password}@localhost:{port}/{name}'.format(
    user=os.environ.get('POSTGRES_USER', 'nodues'),
    password=os.environ.get('POSTGRES_PASSWORD', 'nodues'),
    port=os.environ.get('POSTGRES_PORT', '5432'),
    name=os.environ.get('POSTGRES_DB', 'nodues'),
)

DATABASES = {
    'default': dj_database_url.config(
        # dj_database_url.config() reads DATABASE_URL itself; `default` below
        # only applies if that env var isn't set (i.e. outside Compose).
        default=_local_db_url,
        conn_max_age=600,  # persistent connections — avoids reconnecting every request under load
    )
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
# Only used by `collectstatic` (Docker/production) — served by WhiteNoise from
# the Django process itself, so nginx doesn't need a shared static volume.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STORAGES = {
    # Required explicitly since Django 4.2: defining STORAGES at all replaces
    # the old STATICFILES_STORAGE *and* DEFAULT_FILE_STORAGE defaults, not
    # just the one key you set. Omitting 'default' left Document.file (and
    # any other FileField/ImageField — i.e. every document upload) with no
    # storage backend configured at all, failing every upload with a 500.
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Session cookie works same-origin via the Vite dev proxy (/api -> :8000).
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Uploaded documents (kept out of the static web root; served via access-checked views).
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploaded_media')

# Match main/api.py::MAX_UPLOAD_BYTES (10 MB) so a normal-sized upload is held
# in memory instead of round-tripping to a temp file on disk. Django's default
# here is 2.5 MB, which doesn't reject anything larger — it would just add an
# unnecessary disk write for every document upload at this size.
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
